name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
          
    - name: Restore dependencies
      run: dotnet restore SEP490.AffiliateNetwork.sln
      working-directory: SEP490.AffiliateNetwork
    
    - name: Build
      run: dotnet build SEP490.AffiliateNetwork.sln --no-restore
      working-directory: SEP490.AffiliateNetwork
    
    - name: Test
      run: dotnet test SEP490.AffiliateNetwork.sln --no-build --verbosity normal
      working-directory: SEP490.AffiliateNetwork
