name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Adds manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: SEP490.AffiliateNetwork
    - name: Build
      run: dotnet build --no-restore
      working-directory: SEP490.AffiliateNetwork
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: SEP490.AffiliateNetwork